services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db_portfolio
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
      - APP_USER=${DB_USER}
      - APP_USER_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle_data: